title: "AI Texts"
description: "Here is some AI-generated staff made by Neiruha"

# Тема для всех страниц
theme: "jekyll-theme-cayman"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

collections:
  stories:
    output: true
    permalink: /stories/:name/

# Настройки по умолчанию для постов и коллекций
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      theme: "jekyll-theme-cayman"

  - scope:
      path: "stories"
      type: "pages"
    values:
      layout: "post"
      theme: "jekyll-theme-cayman"

# Базовый URL для корректных ссылок
baseurl: "/AI"
