title: "AI Stories"
description: "This dataset of AI-generated stories made by Neiruha"

theme: "jekyll-theme-cayman"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

collections:
  stories:
    output: true
    permalink: /stories/:name/

defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
